# VHS tape file for demonstrating the `generate` command
# Run with: vhs demo/generate.tape

Output demo/generate.gif

Set Shell "zsh"
Set FontSize 18
Set Width 1400
Set Height 700
Set Padding 20
Set Theme "Dark+"

Type "gh security-config generate"
Enter
Sleep 2s
Type "github"
Enter
Sleep 2s
Type "callmegreg-6byeyj.ghe-test.net"
Enter
Sleep 1s
Down
Down
Sleep 1s
Up
Up
Sleep 1s
Enter
Sleep 2s
Sleep 2s
Type "y"
Sleep 2s
Type "n"
Sleep 2s
Type "Default Enterprise Config"
Enter
Sleep 2s
Type "Enforced secret scanning and push protection."
Enter
Sleep 2s
Down
Sleep 1s
Up
Sleep 1s
Enter
Sleep 1s
Enter
Sleep 1s
Enter
Sleep 1s
Enter
Sleep 1s
Enter
Sleep 1s
Enter
Sleep 1s
Enter
Sleep 2s
Type "y"
Sleep 3s
Type "y"
Sleep 25s
